### ISSUE TITLE
AttachmentAdapter performance

### ISSUE THREAD

**Issue by alexfu** [Buglife/buglife-android#3]
I found that the `AttachmentAdapter` had performance issues when it came to the example app. Most noticeably was the touch selector on the attachments was very janky. The problem ended up being the attached walter image. Being that it's 1201 x 1600 in size and that the bitmaps are not scaled down for thumbnail size, a lot of time is being spent on rendering this image. Take a look at the following [screenshot](https://user-images.githubusercontent.com/987398/28667539-ed0596e0-7299-11e7-9b9c-86586bf3f2e9.png). More info on the bars can be found [here](https://developer.android.com/studio/profile/dev-options-rendering.html).

A naive solution could be to simply remove the walter image but the API allows users to attach any arbitrary image, so that wouldn't fix the root problem. A better solution would be to scale the images down to a much smaller size for thumbnail usage. 

Doing so, however, poses another concern regarding memory usage. If the bitmap were to be scaled down, there will be two bitmaps in memory (scaling creates a copy of the original bitmap) which would be a problem for lower end devices (resulting in an OOM exception). This issue can most likely be addressed later when the issue actually arises.

Also, the adapter should avoid inflating a layout unless `convertView` is null.

**Comment by alexfu** [comment]
I'd be happy to submit a PR for this issue.

**Comment by schukin** [comment]
Ah yes; so since walter.jpg is in the `drawable` resource directory (vs. `drawable-nodpi`), it is being scaled up due to the screen density when it is decoded to a Bitmap. i.e. on a Pixel XL, walter.jpg becomes 4204x5600, however a regular screenshot is only 1440x2560. Commit 894db89 removes walter.jpg from the example report, since we only use this image for internal testing / optimization, and "typical" screenshots shouldn't be nearly as slow.

That said, as you pointed out this isn't really a solution to the root problem. And yes, we'll happily accept a PR! 🙌

**Comment by alexfu** [comment]
@schukin interesting, I hadn't realized that images under `drawable` get scaled. makes sense now that I think about it.

![](https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy.gif)
