### ISSUE TITLE
Is SYSTEM_ALERT_WINDOW Permission necessary?

### ISSUE THREAD

**Issue by lazyFloyd** [Buglife/buglife-android#38]
Hi guys,

today we wanted to rollout app update, which included Buglife as a new feature, but then we got the [following message in Google Play Console](https://imgur.com/a/VeX11b5) saying that users are going to need accept android.permission.SYSTEM_ALERT_WINDOW permission in order to get the latest update. Since our app has a lot of users, we think many of them will reject upgrading to the latest version of the app, what forced us to temporarily disable Buglife SDK.

So, is this permission really necessary in your SDK? Even [Android Documentation](https://developer.android.com/reference/android/Manifest.permission.html#SYSTEM_ALERT_WINDOW) doesn't recommend using this flag as well.

I will be grateful for any explanation :)

**Comment by schukin** [comment]
Sorry for the trouble! 

The `android.permission.SYSTEM_ALERT_WINDOW` is included in order to present activities / dialogs from anywhere in the host app, i.e. confirmation dialogs for showing the bug reporter, or showing the bug reporter itself. You can find other examples of this [here](https://github.com/noln/system-alert-window-example) and [here](https://gist.github.com/bjoernQ/6975256).

Requiring a new permission definitely sucks though. :-/ We're happy to entertain alternative approaches, if you have any ideas!
