### ISSUE TITLE
custom BugReporter impl

### ISSUE THREAD

**Issue by dgluhovic** [Buglife/buglife-android#42]
We are trying to send bug reports to our backend.  Afaict there's no way to provide a custom bug reporter.  Please consider adding something like 

`    public static void initWithBugReporter(@NonNull Application application, @NonNull BugReporter bugReporter, @NonNull String apiKey) {
        mClient = new Client(application, bugReporter, new ApiIdentity.ApiKey(apiKey));
    }`

or better yet

`public static void initWithBugReporter(@NonNull Application application, @NonNull BugReporter bugReporter) {
        mClient = new Client(application, bugReporter, ApiIdentity.NONE);
    }`

Also, this is dangerous on network error retry, for example: https://github.com/Buglife/buglife-android/blob/master/src/main/java/com/buglife/sdk/Report.java#L89

**Comment by schukin** [comment]
Hi @dgluhovic - have you tried using one of the built-in Buglife [integrations or webhook API](https://buglife.com/docs/integrations)?

**Comment by dgluhovic** [comment]
@schukin we'd previously integrated with Asana but now want to point to our backend with user auth token, no api keys.

**Comment by schukin** [comment]
Gotcha. So while developers are free to maintain their own fork of the Buglife SDK, we only officially support on-premise / custom backends as part of our [Enterprise plan](http://buglife.com/pricing). Reason for this is because new versions of our client SDKs occasionally contain breaking changes to their contracts with the backend API, which subsequently must be updated for the new SDK releases while maintaining backward compatibility. 

I'd love to learn more about the reasons for going w/ a custom backend, and where the existing Buglife backend is falling short. :)

**Comment by dgluhovic** [comment]
Understood, was worth a try:)  We're planning to store the data in our primary db and integrate with our admin pages.  A public API is feasible in theory but more work than we’re allocating for.  Not sure our service has any such hooks at this point.

Thanks for the library, very handy.  Please consider removing that log file delete.
